### ISSUE TITLE
Na interface pública do clipping deve exibir data da fonte, autor da fonte e link da fonte 

### ISSUE THREAD

**Issue by sousajul** [bireme/bvs-noticias#10]
![image](https://cloud.githubusercontent.com/assets/13439949/15711825/24582ba8-27e6-11e6-8f95-5f1ffe72b20a.png)
- Os conteúdos devem ser apresentados abaixo de Related Posts.
- No link da fonte não remete para a fonte original.

**Comment by wilsonmoura** [comment]
@sousajul 

Criamos o custom post type Clipping e ajustamos o template do mesmo para que mostre essas informações.

Favor validar.

**Comment by wilsonmoura** [comment]
Issue encerrado por inatividade. Vamos reabrir essa atividade caso necessário.
