### ISSUE TITLE
Ao abrir uma notícia, o menu e uma caixa de busca são exibidos mesmo sem ter sido configurados nos widgets

### ISSUE THREAD

**Issue by sousajul** [bireme/bvs-noticias#11]
![image](https://cloud.githubusercontent.com/assets/13439949/15712234/ef6f941a-27e7-11e6-9ffc-6354cfd66a26.png)

**Comment by wilsonmoura** [comment]
@sousajul o menu e a caixa de pesquisa estão cravados nos templates das notícias/clippings. No entanto, verificamos que a caixa de pesquisa está presente nos wireframes de visualização das notícias/clippings. Por favor, informe se essa caixa de pesquisa deve ou não ser removida desses templates, mesmo estando presente nos wireframes.

**Comment by sousajul** [comment]
Como está cravado nos templates, percebemos que ao utilizar o menu e cx. de pesquisa na home os mesmos são duplicados na página da noticia. Neste caso, verificar qual a melhor forma de manter as opções na página da noticia sem que seja duplicado.

**Comment by wilsonmoura** [comment]
@sousajul 

Conforme conversamos, retiramos a caixa de pesquisa e o menu que estavam fixos nos templates dos conteúdos.

Favor validar.

**Comment by marcoslmori** [comment]
Fiz o teste e a pesquisa não apareceu na noticias.  Se comportou de acordo com os ajustes

**Comment by sousajul** [comment]
Ok validado também.
