### ISSUE TITLE
Os related posts estão sendo publicados mesmo sem ter sido configurado

### ISSUE THREAD

**Issue by sousajul** [bireme/bvs-noticias#12]
- É importante que tenha essa funcionalidade
- Qual o critério de relacionamento?
- Como configura?
- Como ele é publicado?

**Comment by wilsonmoura** [comment]
A publicação de posts relacionados é automático ao ativar o plugin Contextual Related Posts.
O plugin possibilita configurar em quais tipos de post types o recurso estará disponível (vide `Configurações > Related Posts > General Options > Automatically add related posts to`).
Há também a possibilidade de definir quais post types serão utilizados no processo de relacionamento (vide `Configurações > Related Posts > List Tuning Options > Post types to include in results`).
O critério de relacionamento não é explícito na documentação do plugin. Porém, é possível configurar se o algoritmo usará o título, conteúdo do post e quantidade de palavras utilizadas no mesmo. Estamos investigando e acreditamos que essa análise será melhor fundamentada tendo massa crítica de conteúdo. Essa avaliação será documentada na issue #20.

**Comment by sousajul** [comment]
Ok, aguardamos ter massa critica para avaliar melhor.
