### ISSUE TITLE
Em News Clipping incluir a funcionalidade de [add] adicionar mais fontes no campo News Source

### ISSUE THREAD

**Issue by sousajul** [bireme/bvs-noticias#13]
- Essa implementação é importante para manter o fluxo de navegação para preenchimento dos campos;
- Ao add uma nova fonte já deve ser mostrado na lista de fontes para seleção;
- Atualmente só apresenta após publicar o news clipping, mas como é campo obrigatório é impossível publicar sem o preenchimento do campo.

![image](https://cloud.githubusercontent.com/assets/13439949/15713114/66e610c0-27eb-11e6-8212-64b9cdd4de6e.png)

**Comment by wilsonmoura** [comment]
Considerando que vamos separar a notícia do clipping em tipos de conteúdos diferentes, não será mais necessário esse campo no formulário, pois o mesmo aparecerá como uma lista do lado direito do formulário de entrada no custom post type Clipping.

**Comment by marcoslmori** [comment]
documentar

**Comment by sousajul** [comment]
Como os formulários foram separados, em News não é necessário manter o campo Sources já que é a noticia original. Este campo é proveniente apenas do Clipping.

**Comment by wilsonmoura** [comment]
Issue encerrado por depreciação. Vamos reabrir essa atividade caso necessário.

**Comment by wilsonmoura** [comment]
Issue encerrado por inatividade. Vamos reabrir essa atividade caso necessário.
