### ISSUE TITLE
Quando o nível 2 não for utilizado, o conteúdo/ texto deve ocupar toda a página

### ISSUE THREAD

**Issue by sousajul** [bireme/bvs-noticias#14]
- Para ter um melhor aproveitamento do espaço.
- Melhora a navageção e visualização do conteúdo;
- O nível 2 deve ser mantido caso o usuário queira utilizá-lo.

![image](https://cloud.githubusercontent.com/assets/13439949/15713280/2f1c343e-27ec-11e6-91c9-f94d88549bc5.png)

**Comment by wilsonmoura** [comment]
@sousajul 

Implementamos reajustes automáticos de layout quando a área de widgets do nível 2 não está sendo utilizada.

Favor validar.

**Comment by marcoslmori** [comment]
Fizemos os testes, mas é preciso de orientação e documentação no sentindo que se a pessoa quiser que o segundo nivel tenha colunas iguais da primeira página tem que prever o comportamento da configuração do tamanho das imagens do banner e do logo

**Comment by marcoslmori** [comment]
Fizemos os testes e funcionou corretamente, mas tem que tomar atenção na definição da altura das imagens para não quebrar as colunas.
