### ISSUE TITLE
Qual a função do news type no menu vertical do WP?

### ISSUE THREAD

**Issue by sousajul** [bireme/bvs-noticias#15]
![image](https://cloud.githubusercontent.com/assets/13439949/15713468/f036b202-27ec-11e6-8f34-af4c9b20741d.png)

**Comment by wilsonmoura** [comment]
A custom taxonomy News Type foi identificada como uma duplicação do recurso disponível no formulário de entrada de uma notícia.
Vamos implementar no issue #17 dois custom post types distintos para notícia e clipping.
