### ISSUE TITLE
Substituir o rótulo do campo "News Clipping" por "News Type"

### ISSUE THREAD

**Issue by sousajul** [bireme/bvs-noticias#16]
![image](https://cloud.githubusercontent.com/assets/13439949/15713640/9e1f7200-27ed-11e6-9eb4-6330207ac576.png)

**Comment by wilsonmoura** [comment]
Após a resolução do issue #15, esse ajuste não será mais necessário, pois esse custom field deixará de ser exibido no formulário de entrada de dados.

**Comment by marcoslmori** [comment]
Necessário atualizar a documentação

**Comment by marcoslmori** [comment]
Issue será fechado e criado um específico para documentação
