### ISSUE TITLE
No widget "Ultimate Posts" em Filter > Post types separar os tipos de posts em "news clipping" e "original news"

### ISSUE THREAD

**Issue by sousajul** [bireme/bvs-noticias#17]
- Essa funcionalidade permitirá separar a exibição das noticias originais e clipping.

![image](https://cloud.githubusercontent.com/assets/13439949/15713774/2fa7f328-27ee-11e6-8c5b-a63e491cd75e.png)

**Comment by wilsonmoura** [comment]
Será implementado novo custom post type para Clipping. Dessa forma, será possível filtrar por esse tipo de conteúdo.
Decisão tomada em conjunto com @barrosjo

**Comment by wilsonmoura** [comment]
@sousajul 

Adicionamos o custom post type Clipping para que o mesmo possa ser selecionado nos filtros do widget Ultimate Posts.

Favor validar.

**Comment by marcoslmori** [comment]
Validei na instância de teste está tudo ok, mas tem de atualizar na documentação
