### ISSUE TITLE
Incluir paginação das noticias como apresentado no wireframe

### ISSUE THREAD

**Issue by sousajul** [bireme/bvs-noticias#18]

**Comment by wilsonmoura** [comment]
Será avaliado essa melhoria no plugin Ultimate Post Widget, pois o mesmo não possui esse recurso.

**Comment by wilsonmoura** [comment]
@sousajul 

A paginação foi implementada conforme os wireframes.

Favor validar.

**Comment by marcoslmori** [comment]
Testei diminuindo a quantidade de posts a mostrar no site publico  no widget ultimate posts e funcionou corretamente.
