### ISSUE TITLE
Opções de tema do plugin bvs noticias não está habilitado para ajustes

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-noticias#19]
![image](https://cloud.githubusercontent.com/assets/10047460/15719219/53e67d7e-2805-11e6-9cc8-6e19ec370f61.png)

**Comment by marcoslmori** [comment]
Na opçoes do Tema, na inserção de imagem da galeria tanto  do banner como do logo o recurso de alinhamento não está respeitando o configurado pelo usuário

![image](https://cloud.githubusercontent.com/assets/10047460/16817734/92e9eb38-491a-11e6-8810-627f6a300c86.png)

**Comment by wilsonmoura** [comment]
@marcoslmori 

A opção de alinhamento não faz parte dos metadados da imagem. Por esse motivo, esse recurso não deve ser considerado pelo usuário.

Favor documentar esse comportamento.

**Comment by wilsonmoura** [comment]
@marcoslmori 

O atributo de alinhamento da imagem é sobreposto pelos ajuste de CSS do tema do plugin. Esse recurso de inclusão de imagem foi implementado para facilitar as ações do usuário.

Favor documentar.
