### ISSUE TITLE
Tradução da opção "theme options" está sendo mostrado só quando o plugin da BVS está ativado

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-noticias#27]
O comportamento correto é que plugin de noticias não seja dependente do plugin da bvs

![image](https://cloud.githubusercontent.com/assets/10047460/17068462/797cebd2-5027-11e6-9a49-e5ad8e4f8bfd.png)

**Comment by wilsonmoura** [comment]
Issue encerrado por inatividade. Vamos reabrir essa atividade caso necessário.
