### ISSUE TITLE
Labels e helps do formulário de clipping não estão sendo traduzidos

### ISSUE THREAD

**Issue by marcoslmori** [bireme/bvs-noticias#28]
![image](https://cloud.githubusercontent.com/assets/10047460/17155878/562b914a-535d-11e6-9257-d2a76149bf8b.png)

**Comment by wilsonmoura** [comment]
@marcoslmori esses labels/helps são gerados no plugin ACF. Sendo assim, não é possível traduzir, pois as traduções precisam estar disponíveis no respectivo plugin.
