### ISSUE TITLE
Só é possível ativar o tema BVS News se o plugin for ativado na rede

### ISSUE THREAD

**Issue by sousajul** [bireme/bvs-noticias#29]
Ao ativar o plugin apenas no subportal no qual será utilizado o tema não aparece para ser ativado.

Se ativar o tema na rede os custons post type (notícias e clipping) aparecem também na rede (site principal).
- Esse comportamento pode gerar confusão uma vez que o administrador pode passar a incluir registros no site principal ao invés do subportal.

**Comment by wilsonmoura** [comment]
@sousajul 

Nós modificamos o plugin para que o mesmo seja ativado somente no menu da rede.
Ajustamos também os CPTs para que os mesmos sejam exibidos somente quando o tema do plugin estiver ativado.

Favor validar.

**Comment by sousajul** [comment]
Wilson validado.
