### ISSUE TITLE
Desenvolver o guia rápido de uso do plugin Notícias

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/bvs-noticias#3]

**Comment by marcoslmori** [comment]
Primeira versão do guia rápido do plugin de Noticias
https://github.com/bireme/bvs-noticias/wiki/Guia-R%C3%A1pido-do-Plugin-de-Not%C3%ADcias
- Solicitado para o MIP validar o uso em 18/05/2016
- Criado instâncias de teste para validar o guia de uso
- Reunião para finalizar o documento em: 25/05/2016
- http://agenda.bireme.org/view_entry.php?id=62826&date=20160525

**Comment by marcoslmori** [comment]
Finalizado 1. versão da wiki "Instalação do plug-in de Notícias da BVS" baseado na instalação do plugin da BVS

https://github.com/bireme/bvs-noticias/wiki/Instala%C3%A7%C3%A3o-do-plug-in-Not%C3%ADcias-da-BVS

**Comment by wilsonmoura** [comment]
Versão 1.0 do guia concluído com sucesso!
