### ISSUE TITLE
Criar RSS por categoria

### ISSUE THREAD

**Issue by sousajul** [bireme/bvs-noticias#33]
Atualmente o plugin apresenta um link de RSS por categoria, mas o mesmo não funciona.
Ex: http://sms.sp.bvs.br/noticias/category/contribuicao-mensal/
http://sms.sp.bvs.br/noticias/category/divulgacao/

Verificar possibilidade de criar RSS com filtro por categoria

**Comment by wilsonmoura** [comment]
@sousajul Os ajustes foram aplicados no ambiente de produção. Favor validar.
