### ISSUE TITLE
Atualizar labels de tradução para português e espanhol

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/bvs-noticias#7]
Revisar também o idioma inglês.

https://github.com/bireme/bvs-noticias/tree/master/languages

**Comment by wilsonmoura** [comment]
Idioma português encontra-se atualizado.

**Comment by wilsonmoura** [comment]
@marcoslmori proceder com a revisão do idioma espanhol.

**Comment by marcoslmori** [comment]
Feito, verificar se o formato está ok?
