### ISSUE TITLE
Configurar para que o logo e banner sejam inseridos via aparência > opções do tema > cabeçalho, como o plugin da BVS

### ISSUE THREAD

**Issue by sousajul** [bireme/bvs-noticias#8]
![image](https://cloud.githubusercontent.com/assets/13439949/15710813/feb082f0-27e1-11e6-83bd-d21ad54b7280.png)
- Melhora a curva de aprendizado do plugin, pois segue o padrão já utilizado no plugin da BVS;
- Atividade se torna mais intuitiva e prática;
- Não exige conhecimentos em códigos HTML;

**Comment by wilsonmoura** [comment]
O desenvolvimento desse issue impacta a abordagem de solução do issue #6.
@sousajul será necessário investigar dependências inerentes à funções do plugin Polylang.
O comportamento mencionado era compatível com o Multilanguage Framework, antigo plugin de tradução usado no plugin BVS-Site.

**Comment by wilsonmoura** [comment]
@sousajul 

Os ajustes foram realizados de acordo com os mesmos recursos implementados no plugin BVS-Site.

Favor validar.

**Comment by sousajul** [comment]
Fiz o teste e está Ok.
