### ISSUE TITLE
O plugin BVS Notícias ao ser instalado deve assumir o cabeçalho e rodapé do site principal 

### ISSUE THREAD

**Issue by sousajul** [bireme/bvs-noticias#9]
- O plugin BVS Notícias deve se comportar como os plugins LIS e Direve em relação à identidade visual, para que não tenham ações de um webmaster quando tiver um site principal.
-  Para customizações personalizadas de banner o logo utilizar a solução via aparencia > opções do tema > cabeçalho

**Comment by wilsonmoura** [comment]
@sousajul para desenvolver o plugin BVS Notícias, não foi possível seguir a mesma estrutura dos plugins LIS e DirEve, que utilizam WP páginas que consomem webservices do FI-ADMIN. Como todo o fluxo de trabalho é feito via WP, foi necessário adotar novo tema, o que inviabiliza herdar a identidade visual de cabeçalho e rodapé do site principal. A customização personalizada de logo e banner já está sendo tratada na issue #8.

**Comment by sousajul** [comment]
ok.
